import type { Metadata } from "next";
import { Open_Sans  } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";


// const helavicta = localFont({
//   src: "../fonts/Helvetica-Bold.ttf",
//   variable: '--font-helavicta',
//   display: 'swap',
// })
const openSans = Open_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:["400","500","600","700"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${openSans.className}  h-full antialiased`}
    >
      {/* <h1 className="uppercase font-bold text-white text-2xl">Nexula</h1> */}
      <body className="min-h-full dark">
        {children}
      </body>
    </html>
  );
}
